image-js/image-js

.travis.yml, package.json, src/compute/countAlphaPixels.js, src/environment.js, src/extend.js, src/image.js, src/load.js, src/operator/extract.js, test/node/core/load.js, test/node/core/loadPNG.js, test/node/core/save.js, test/node/operator/extract.js, test/node/roi/extract.js, test/node/roi/internalMapID.js, test/node/roi/mask.js
=> add support for loading 16bit png

src/transform/scale/nearestNeighbor.js, test/node/transform/scale/nearestNeighbor.js
tests with images from photoshop are failing. need to alter the algorithm
=> add nearest neighbor tests

src/image/extend.js, src/image/filter/__tests__/flipX.js, src/image/filter/__tests__/flipY.js, src/image/filter/flipX.js, src/image/filter/flipY.js
=> add flipX and flipY filters

src/image/filter/__tests__/flipX.js, src/image/filter/flipX.js, src/image/kind.js, src/image/kindNames.js
-wrote method for flipX which flips the image on the horizontal axis based on the data array instead of the getpixel() methods
-fixed bug in kind.js s.t. CMYK's alpha = 0 and CMYKA's alpha = 1
=> filter/flipX.js modification and bug fix in kind.js

src/image/extend.js, src/image/transform/__tests__/warping.js, src/image/transform/warping.js
Feature to transform a quadrilateral to a rectangle.
(@targos : https://en.wikipedia.org/wiki/Quadrilateral)
=> feat: Add the warping with 4 points 

package-lock.json, src/image/extend.js, src/image/morphology/__tests__/dilate.js, src/image/morphology/__tests__/erode.js, src/image/morphology/dilate.js, src/image/morphology/erode.js
Add erode and dilate functions. They will be used by others morphology transformations (http://docs.opencv.org/2.4/doc/tutorials/imgproc/opening_closing_hats/opening_closing_hats.html)
=> Morphology transformations

src/image/morphology/dilate.js, src/image/morphology/erode.js
fix: errors in some cases with erode and dilate
=> Errors with some particular sizes of kernel

src/image/morphology/blackHat.js, src/image/morphology/closing.js, src/image/morphology/morphologicalGradient.js, src/image/morphology/opening.js, src/image/morphology/topHat.js
errors in the call of the morphological transforms
=> Errors with the parameters (never used...)

package.json
=> fix(package): update blob-util to version 2.0.2

index.d.ts
Fixes: https://github.com/image-js/image-js/issues/425
=> fix: export all TS symbols

src/image/roi/Roi.js
This saves a huge amount of memory and some time on big images.
=> fix: use contourMask to compute hullMask

index.d.ts
Address #520. 
I also applied the prettier formatting rules.
=> Add basic Stack type definition

src/image/filter/__tests__/addSubtract.js, src/image/filter/subtractImage.js
- chore: change testcase to use array string
- feat: subtract image first copy the image
=> subtractImage

src/image/roi/Roi.js
@lpatiny shall we make some test images (e.g., perfect circles) to test those functions
=> fix: roundness was not 1 for perfect circle

src/image/Image.js
=> doc: image from matrix of values

index.d.ts
Please, merge this PR. I need the `setChannel()` method on my project and for some reason, it didn't have a definition. I just added one based on the doc.
=> feat: add Typescript definition to setChannel() method

index.d.ts
Added some type definition to some methods. Please check if I did something wrong since I am just a beginner to image-js.
=> fix: add TypeScript definition to many methods

index.d.ts, src/image/operator/paintLabels.js, src/image/operator/paintPolygon.js, src/image/operator/paintPolygons.js, src/image/operator/paintPolylines.js
- Added more Typescript definitions
- Fixed some typos and wrong types in the paintLabels, painPolygon, paintPolygons and paintPolylines function documentations
=> Fix: more typescript definitions

.github/workflows/nodejs.yml, index.d.ts, package.json
close: https://github.com/image-js/image-js/issues/637
=> chore: add type for insert method

.github/workflows/typedoc.yml, README.md
- **docs: fix links to merged repository**
- **docs: add ssim export to typedoc entries**
=> Fix links to repo and add ssim to typedoc generation

.github/workflows/typedoc.yml, typedoc.json
- Set a name
- Move entry points to typedoc.json to avoid config in two places
=> chore: consolidate typedoc config
